apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: back-helm
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: back-helm
      version: 18.0.0
  values:
    auth:
      database: wordpress
      username: wp_user
      password: wp_pass
    primary:
      persistence:
        enabled: true
        size: 8Gi
        accessModes:
          - ReadWriteOnce
