apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: rootpass
  MARIADB_USER: wpuser
  MARIADB_PASSWORD: wppass
  MARIADB_DATABASE: wordpress
