apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 1m
  path: ./../../apps/front-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: front-helm
