apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frontend-testing
  namespace: flux-system
spec:
  interval: 1m
  path: ./../../apps/frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mi-front
